# Generated by Django 4.2.24 on 2025-09-12 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key/name', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed', max_length=255)),
                ('table_name', models.CharField(blank=True, help_text='Database table affected by the action', max_length=100)),
                ('record_id', models.PositiveIntegerField(blank=True, help_text='ID of the record affected', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the browser/client')),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional data related to the action')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_audit_logs_user'), models.Index(fields=['table_name'], name='idx_audit_logs_table'), models.Index(fields=['created_at'], name='idx_audit_logs_created')],
            },
        ),
    ]
