# Generated by Django 4.2.24 on 2025-09-12 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service unit (e.g., Choir, Ushers, Protocol, Media)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the service unit's purpose and activities", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this service unit was created')),
                ('admin', models.ForeignKey(blank=True, help_text='Admin user responsible for managing this service unit', limit_choices_to={'role__in': ['SuperAdmin', 'ServiceUnitAdmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Unit',
                'verbose_name_plural': 'Service Units',
                'db_table': 'service_units',
                'ordering': ['name'],
            },
        ),
    ]
