# Generated by Django 4.2.24 on 2025-09-12 10:22

import apps.buildings.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the building (e.g., Main Hall, Guest House A)', max_length=150)),
                ('location', models.CharField(blank=True, help_text='Physical location or address of the building', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the building and its facilities', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this building was added to the system')),
                ('created_by', models.ForeignKey(help_text='Super admin who created this building', limit_choices_to={'role': 'SuperAdmin'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_buildings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room number or identifier (e.g., 101, A1, Room 1)', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Number of beds/people this room can accommodate', validators=[django.core.validators.MinValueValidator(1)])),
                ('has_toilet', models.BooleanField(default=False, help_text='Whether this room has a private toilet')),
                ('has_washroom', models.BooleanField(default=False, help_text='Whether this room has a private washroom/bathroom')),
                ('is_allocated', models.BooleanField(default=False, help_text='Whether this room is currently allocated to someone')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this room was added to the system')),
                ('building', models.ForeignKey(help_text='Building this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='Room picture/photo', upload_to=apps.buildings.models.room_picture_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Optional caption or description for the picture', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary/main picture for the room')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this picture was uploaded')),
                ('room', models.ForeignKey(help_text='Room this picture belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='buildings.room')),
            ],
            options={
                'verbose_name': 'Room Picture',
                'verbose_name_plural': 'Room Pictures',
                'db_table': 'room_pictures',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building'], name='idx_rooms_building'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_allocated'], name='idx_rooms_allocated'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'room_number'], name='idx_rooms_building_number'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'room_number'), name='unique_room_per_building'),
        ),
    ]
