# Generated by Django 4.2.24 on 2025-09-12 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the report template', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this report shows')),
                ('report_type', models.CharField(choices=[('occupancy', 'Occupancy Report'), ('allocation', 'Allocation Report'), ('service_unit', 'Service Unit Report'), ('member', 'Member Report'), ('building', 'Building Report'), ('custom', 'Custom Report')], help_text='Type of report', max_length=20)),
                ('query_config', models.JSONField(default=dict, help_text='Configuration for the report query (filters, parameters, etc.)')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this report can be viewed by all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this report template', on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used for this execution')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the report execution', max_length=20)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Cached report result data')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Time taken to execute the report in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(help_text='User who executed the report', on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Report template that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'db_table': 'report_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
