# Generated by Django 4.2.24 on 2025-09-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service_units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_unit',
            field=models.ForeignKey(blank=True, help_text='Service unit this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='service_units.serviceunit'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_users_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['service_unit'], name='idx_users_service_unit'),
        ),
    ]
