# Generated by Django 5.2.5 on 2025-09-15 19:50

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture/avatar', null=True, upload_to=apps.authentication.models.user_avatar_path),
        ),
    ]
