# Generated by Django 4.2.24 on 2025-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='User settings and preferences stored as JSON'),
        ),
    ]
