# Generated by Django 4.2.27 on 2025-12-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('PortalManager', 'Portal Manager'), ('Pastor', 'Pastor'), ('Deacon', 'Deacon'), ('Member', 'Unit Member')], default='Member', help_text='User role in the system', max_length=30),
        ),
    ]
